### ISSUE TITLE
The file deletion method throws an error after deleting files.

### ISSUE THREAD

**Issue by yatolstoy** [shevernitskiy/amo#16]
This is a issue about fix error.

I expect that if the files are successfully deleted, my script should execute next.
Currently, the method ```await amo.file(amoAccount.drive_url).deleteFiles(fileIds)``` throws an ```Error: 204 No Content``` on successful execution.

Based on AmoCRM [documentation](https://www.amocrm.ru/developers/content/files/files-api#%D0%A3%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2) 
you can see that code 204 comes when files are successfully deleted.
I checked, the files are indeed deleted from amoCRM.

As I found out the error occurs because the checkError method of the RestClient object specifies that if the response code is 204, the code throws an error ```throw new NoContentError(`${res.status} ${res.statusText}, ${res.statusText}, ${res.url}`);``` (line 75).

Because of this collision I do not get further script execution.

To be honest, I haven't found a more elegant solution yet except to check the method and URL directly ```} else if (res.status === 204 && !(res.url.includes('v1.0/files') && res.method === 'DELETE'))) { ```

Any ideas?

**Comment by shevernitskiy** [comment]
Amo dicedes to use 204 instead of 404 or 406 for many other cases. Obviously 200 codes shouldn't throws.
If 204 will not throws, every response type will be union with `no content` type, user will do type narrownig on every call. That's not so convenient.

If you want to dig into this problem, you can investigate 204 case for other methods. Then we can decide should it be refactored or not (cause it breaking change)
If not, the i can suggest `try catch` with empty `catch `

I'm not using amo at all, so a not 100% what is better solution, though.

**Comment by yatolstoy** [comment]
> Амо решает использовать 204 вместо 404 или 406 во многих других случаях. Очевидно, что 200 кодов не должны выдаваться. Если 204 не выдаст, каждый тип ответа будет объединен с `no content`типом, пользователь будет сужать тип при каждом вызове. Это не так удобно.
> 
> Если вы хотите углубиться в эту проблему, вы можете изучить случай 204 другими методами. Затем мы сможем решить, следует ли его рефакторить или нет (потому что это критическое изменение). Если нет, то я могу предложить `try catch`пустой`catch `
> 
> Я вообще не использую amo, поэтому не знаю на 100%, какое решение лучше.
> 
> PS: может быть, будет лучше просто обработать этот особый случай на стороне пользователя и рассматривать 204, поступающий в catch, как нормальное выполнение...
> 
> PPS: я выбрал смайлик в описании репозитория специально из-за таких случаев

I really like using your library.
The idea of using try catch will work, but, in my opinion, it will clog the code with one-type inserts (violating the DRY principle).
Plus it's not convenient, because you have to keep this case in your head all the time.

I examined the rest of the API methods for 204 response status. We get a 204 code when:
1. In leads when lead with specified id is not found [link](https://www.amocrm.ru/developers/content/crm_platform/leads-api#lead-detail)
2. When the pipeline has been successfully removed [link](https://www.amocrm.ru/developers/content/crm_platform/leads_pipelines#%D0%A3%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2%D0%BE%D1%80%D0%BE%D0%BD%D0%BA%D0%B8)
3. In pipelines/statuses, when the funnel has been successfully removed [link](https://www.amocrm.ru/developers/content/crm_platform/leads_pipelines#%D0%A3%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D1%82%D0%B0%D1%82%D1%83%D1%81%D0%B0-%D0%B2%D0%BE%D1%80%D0%BE%D0%BD%D0%BA%D0%B8)
4. In contacts, when contact with the specified id is not found [link](https://www.amocrm.ru/developers/content/crm_platform/contacts-api#contact-detail)
5. In companies, when company with specified id is not found [link](https://www.amocrm.ru/developers/content/crm_platform/companies-api#company-detail)
6. When unbinding entities, a 204 code is used to say that the entities have been successfully unbinded [link](https://www.amocrm.ru/developers/content/crm_platform/entity-links-api#links-unlink)
7. When deleting fields/group of fields 204 code indicates that the fields have been successfully deleted [link](https://www.amocrm.ru/developers/content/crm_platform/custom-fields#%D0%A3%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D0%BE%D0%BB%D1%8F)
8. In tags for an entity, we get 204 code when no tags are found [link](https://www.amocrm.ru/developers/content/crm_platform/tags-api#%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%82%D0%B5%D0%B3%D0%BE%D0%B2-%D0%B4%D0%BB%D1%8F-%D1%81%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D0%B8)
9. In customers when customer is not found by id [link](https://www.amocrm.ru/developers/content/crm_platform/customers-api#customer-detail)
10. In customers when the customer is remote [link](https://www.amocrm.ru/developers/content/crm_platform/customers-api#transaction-delete)
11. In customers/status when the status was successfully deleted [link](https://www.amocrm.ru/developers/content/crm_platform/customers-statuses-api#customer-status-delete)
12. In customers/segments when a customer segment has been successfully removed [link](https://www.amocrm.ru/developers/content/crm_platform/customers-statuses-api#segment-delete)
13. In users/roles when a role has been successfully deleted [link](https://www.amocrm.ru/developers/content/crm_platform/users-api#role-delete)
14. In webhooks when webhook was successfully removed [link](https://www.amocrm.ru/developers/content/crm_platform/webhooks-api#webhooks-delete)
15. In widgets when widget was successfully disabled [link](https://www.amocrm.ru/developers/content/crm_platform/widgets-api#widget-uninstall)
16. In the list of subscribers of an entity when the searched entity is not found [link](https://www.amocrm.ru/developers/content/crm_platform/subscriptions-api#subscriptions-list)
17.In sources when source was not found [link](https://www.amocrm.ru/developers/content/crm_platform/sources-api#%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%B8%D1%81%D1%82%D0%BE%D1%87%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2)
18.In sources when the source is successfully removed [link](https://www.amocrm.ru/developers/content/crm_platform/sources-api#%D0%A3%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D1%81%D1%82%D0%BE%D1%87%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2)
19.In response templates when no template was found [link](https://www.amocrm.ru/developers/content/crm_platform/chat-templates-api#%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%B0-%D0%BF%D0%BE-ID)
20.In response templates, if the template is successfully deleted [link](https://www.amocrm.ru/developers/content/crm_platform/chat-templates-api#%D0%A3%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%BE%D0%B2)
21.In chats when no messages are found [link](https://www.amocrm.ru/developers/content/chats/chat-api-reference#%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D1%81%D1%82%D0%BE%D1%80%D0%B8%D0%B8-%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B9-%D0%BF%D0%BE-%D1%87%D0%B0%D1%82%D1%83)
22. In chat rooms when typing information is accepted [link](https://www.amocrm.ru/developers/content/chats/chat-api-reference#%D0%9F%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D1%87%D0%B0-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%B8-%D0%BE-%D0%BF%D0%B5%D1%87%D0%B0%D1%82%D0%B0%D0%BD%D0%B8%D0%B5)
23. In files, if no files are found [link](https://www.amocrm.ru/developers/content/files/files-api#%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2)
24. In files, if files are successfully deleted [link](https://www.amocrm.ru/developers/content/files/files-api#%D0%A3%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2)
25. In files, if files associated with the entity are not found [link](https://www.amocrm.ru/developers/content/files/files-api#%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2-%D1%81%D0%B2%D1%8F%D0%B7%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%D1%81-%D1%81%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D1%8C%D1%8E)


As a summary, the following patterns of 204 status application:
1. When an entity is successfully deleted. Delete method, response code 204.
2. If the entity is not found. Get method, response code 204.
3. If the change request is accepted by the server. The Post method, response code 204. (paragraphs 6 and 22)

I think it is reasonable to throw an error in cases 2. However, the other cases can probably be left unhandled.
What do you think?

**Comment by shevernitskiy** [comment]
Yeah, i think we could do a check and not throw for `delete` requests.
As  i understood, it always returns `void`.
But in case of POST methods we can't do response type check in runtime (obviously). And we can't do kinda generic check.
Check for POST and empty body will also produce side effects.
I'll add a check for DELETE, but keep issue for POST for now.

**Comment by yatolstoy** [comment]
> Yeah, i think we could do a check and not throw for `delete` requests. As i understood, it always returns `void`. But in case of POST methods we can't do response type check in runtime (obviously). And we can't do kinda generic check. Check for POST and empty body will also produce side effects. I'll add a check for DELETE, but keep issue for POST for now.

All right. I guess this is the right solution.
I noticed that the post methods in my list don't send the request body and send code 204 on a successful request.
As far as I understand, if I don't handle the error in this case, then referring to the body will cause an error in the runtime. 
Please correct me if I have misunderstood you. Thanks.

**Comment by shevernitskiy** [comment]
There are a sequence of checks...
```ts
if (res.ok !== false && res.status !== 204) return;
if (res.status === 204 && method === "DELETE") return;
if (res.headers.get("Content-Type") === "application/problem+json") {
  throw new ApiError(res.body ? await res.json() : "Error", `${res.status} ${res.statusText}, ${res.url}`);
} else if (res.status === 204) {
  throw new NoContentError(`${res.status} ${res.statusText}, ${res.url}`);
} else {
  throw new HttpError(res.body ? await res.text() : `${res.status} ${res.statusText}, ${res.url}`);
}
 ```
Body will be accessed if all these checks were passed and body is not `undefined `.
POST with 204 response will not pass checks, so the body will not be accessed by lib.
But if you perform raw request by yourself, it's better to do body check before getting any data from it anyway.
And do it in a `try catch` for sure.
