### ISSUE TITLE
NodeJs version >=18

### ISSUE THREAD

**Issue by dmitriyzhuk** [shevernitskiy/amo#17]
Hi, please add to the readme that at least nodejs >=18 is required. 

As of only Node.js version 18, the fetch API is natively available.

**Comment by shevernitskiy** [comment]
There is constraint in package.json.
https://github.com/shevernitskiy/amo/blob/main/scripts/build-npm.ts#L32

**Comment by shevernitskiy** [comment]
Add explicit suppoted version to readme in 023e591969afa661aca3495794ac14f8ea636a9e
