### ISSUE TITLE
Add support of long-term tokens

### ISSUE THREAD

**Issue by belyaev-dev** [shevernitskiy/amo#23]
New update added [long-term access tokens](https://www.amocrm.ru/developers/content/oauth/step-by-step#Долгосрочные-токены) for private integrations. They are the same as the access token, but has longer expire period.

Do we need to update readme? Basically we can use new token as an access_token, but specify expired_at as 5 years or less (depends on real token lifetime)

**Comment by shevernitskiy** [comment]
In a first glace. It wouldn't request any changes to codebase. You can make an a PR to clarify this moment in the readme.

**Comment by belyaev-dev** [comment]
works fine, just requires settings up expires_at manually (and filling up other fields with fake data)

**Comment by shevernitskiy** [comment]
Closed by https://github.com/shevernitskiy/amo/commit/98f7bcc10af1cb230f314410f17b1cb6e13be7ab
