### ISSUE TITLE
Override token renewal flow

### ISSUE THREAD

**Issue by belyaev-dev** [shevernitskiy/amo#27]
If we have an external service that handles tokens flow (ex. refresh every 24h or on error), we need a way to disable/override automatic token renewal in requests library

**Comment by shevernitskiy** [comment]
What kind of external service? I don't understand.

**Comment by belyaev-dev** [comment]
Any. If you're public widgets vendor, you almost always have a core service that manages auth, tokens exchange, partnership logic etc

So, refreshing a token in a widget service without a way to override it gives us at least two problems:
1. You can't manage tokens externally if you want to use amo library - for example, if you keeping all tokens fresh by cron and retreiving account data (cfs/pipelines/etc) in an external cache service
2.. You can't scale widget instances because they don't have single source of truth (tokens). If one of the instances updates the token, second instance will be broken with Token has been revoked error

**Comment by shevernitskiy** [comment]
If we let the user to disable token refresh logic, it will produce invalid token usage situation (will make it possible at least). That's no good. 
I don't know internal partner kitchen, but if you have 1 app to communicate to amo api, it has own token - lib manages with it. If you have many apps to communicate with api - make many tokens for each app.
It just a simple logic and risk separation. Moreover, you can hit the rate limits, if you are using single token for mana many apps.
If it is the only way for partner to use just one token for many apps, could you provide some detailed example please.

**Comment by belyaev-dev** [comment]
Let's make it clear - we're not talking about "many widgets using single token" flow.

It's correct that we need seperate tokens for each app.

But for business purposes we still need to make sure we always have a valid, fresh access token and a single source of truth for analytics.

That's why we have an external service, that:
1) Processes hooks from amoCRM, manages accounts and exchanges tokens
2) Keeps track of licenses of paid widgets
3) Provides admin panel with ability to easily manage installed widgets and other data
and so on

When we're making private widgets, it's cool and easy when library manages auth/token flow by itself. 
When we're going big, it becomes a problem. 

To make sure we always have a fresh token, we need to create Amo instance again for each request (request tokens from Core and prevent their refreshing by @shevernitskiy/amo library). 

Solution we're tested before (subscribe to on_token hook and try to send refreshed tokens to Core instead) creates a problem when Core service has outdated tokens because widget service haven't made any requests for more than 24 hours. Updating the token on Core side will result in widget "token revoked" error - recreating instance with request of new tokens from Core on that error is kinda overkill

**Comment by belyaev-dev** [comment]
Closing this issue until someone needs this
