### ISSUE TITLE
Migrate from AsyncQueue to Bottleneck

### ISSUE THREAD

**Issue by belyaev-dev** [shevernitskiy/amo#5]
I'd like to recommend switching to Bottleneck as way more stable and flexible approach to request queue, just adding a delay for request is way too unpredictable when using on production

```js
export class RestClient {
  private url_base: string;
  private _token?: OAuth;
  private limiter: Bottleneck;

  constructor(
    private base_url: string,
    private auth: OAuthCode | OAuth & Pick<OAuthRefresh, "client_id" | "client_secret" | "redirect_uri">,
    private options?: Options,
  ) {
    this.url_base = `https://${this.base_url}`; 
    if (this.isOAuth(this.auth)) {
      this._token = {
        token_type: this.auth.token_type,
        expires_in: this.auth.expires_in,
        access_token: this.auth.access_token,
        refresh_token: this.auth.refresh_token,
        expires_at: this.auth.expires_at ?? 0,
      };
    }
    this.limiter = new Bottleneck(this.limiterOptions);
  }

  private get limiterOptions(): BottleneckTypes.ConstructorOptions {
    return this.options?.limiterOptions ?? {
      reservoir: 7,
      reservoirRefreshAmount: 7,
      reservoirRefreshInterval: 1000,
      maxConcurrent: 5,
      minTime: 300
    };
  }

  ...
}
```

and then using it as
```js
const res = await this.limiter.schedule(() => fetch(target, {
  method: method,
  headers: init.headers ?? {
    "Authorization": `${this._token?.token_type} ${this._token?.access_token}`,
    "Content-Type": "application/json",
  },
  body: init.payload ? JSON.stringify(init.payload) : undefined,
}));
```

Just a small problem before I prepare a pull request to review. 
Bottleneck is external depedency, and this project is currently loading all external depedencies using CDNs without use of package.json
How to correctly load it then?

**Comment by shevernitskiy** [comment]
Just a small problem before I prepare a pull request to review.
Bottleneck is external depedency, and this project is currently loading all external depedencies using CDNs without use of package.json
How to correctly load it then?

**Comment by shevernitskiy** [comment]
I would prefer to do without external dependencies.
If you want to add a bottleneck, then abstract the rate-limiting mechanism, implement the bottleneck as a simple class, and make the choice between the bottleneck and the async queue in the settings.

**Comment by shevernitskiy** [comment]
And pls make sure, that your implementation would work on deno as well.
